name = "slimeist_aero"
author = "Slimeist"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0eac09279c37f779af14399c9a5a5c77af51e4d7e5005288310b278952588c8c"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.226"

[options]
acceptable-game-versions = ["1.21", "1.21.1"]
datapack-folder = "config/paxi/datapacks"
