name = "slimeist_aero"
author = "Slimeist"
version = "0.0.7"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e38c16a5b2c88e1cecdbe6fac21c0bcf8b5c7bf2f8b1d1e2880e5bd56de5acca"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.226"

[options]
acceptable-game-versions = ["1.21", "1.21.1"]
datapack-folder = "config/paxi/datapacks"
