name = "slimeist_aero"
author = "Slimeist"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "98badcaa1a96df23fe5d2f0e6e883c5be726a583ec38742aeb0f4087a2a8a470"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.226"

[options]
acceptable-game-versions = ["1.21", "1.21.1"]
datapack-folder = "config/paxi/datapacks"
